### DISCUSSION TITLE
How to reduce the font size when printing

### DISCUSSION THREAD

**Discussion by damithc** [MarkBind/markbind#1992] [Q&A] [answered]
Looks like MarkBind V4 has a bigger default font size for printing. Is there a way to adjust the main.css to reduce the font size when printing?

MarkBind V3:
![image](https://user-images.githubusercontent.com/1673303/182859397-aa0bf4ef-e568-4252-94f1-bc34c950df8a.png)

MarkBind V4:
![image](https://user-images.githubusercontent.com/1673303/182859474-40ee6900-6c09-49c0-b3b6-9ba48b0e3f31.png)

**Comment by tlylt** [comment, marked as answer]
For normal body text, doing something like this should work (adjust 0.9rem to any other desired value) to apply the change when print:
```css
@media print {
    body {
        font-size: 0.9rem;  /* Reduce font size when printing */
    }
}

```
