### ISSUE TITLE
Add some left-padding for check boxes

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#165]
![image](https://user-images.githubusercontent.com/1673303/37502553-432c58e4-290e-11e8-939e-3c801f4933fb.png)

The text content seems to have some left-padding but check boxes don't. They should have some left padding too?

**Comment by acjh** [comment]
Looks like a regression bug from MarkBind/markbind-cli#35 (cc: @nicholaschuayunzhi)

**Comment by nicholaschuayunzhi** [comment]
Will look into it

**Comment by nicholaschuayunzhi** [comment]
Identified that the css with textbook.css and the new markbind.css from https://github.com/MarkBind/markbind-cli/pull/35 are responsible for this.

textbook.css
```css
.question-wrapper .radio-list, .question-wrapper .task-list {
    padding-left: 0;
}
```
markbind.css
```css
.radio-list-item, .task-list-item {
    margin: 0 0 0 -1.2em;
}
```

the 0 padding and the -1.2 margin-left results in indentation above. We should disable one to get the desired effect.

**Comment by damithc** [comment]
> We should disable one to get the desired effect.

How should I change the `textbook.css`?

**Comment by acjh** [comment]
It's in [se-edu/se-book](https://github.com/se-edu/se-book): [textbook.css#L20-L24](https://github.com/se-edu/se-book/blob/9a29a6eb94c113acf6b720c915176f1421d713a6/css/textbook.css#L20-L24)

**Comment by damithc** [comment]
> It's in se-edu/se-book: textbook.css#L20-L24

I meant in what way the code should be changed? Just delete? :-)

**Comment by nicholaschuayunzhi** [comment]
> I meant in what way the code should be changed? Just delete? :-)

You could remove 

```css
.question-wrapper .radio-list,
.question-wrapper .task-list {
    list-style: none;
    padding-left :0;
}
```
2103 website:
- [`css/main.css`](https://github.com/nus-cs2103/website-base/blob/8206b5043a77dff1454d6b0e06cd6eb6140aba62/css/main.css#L20-L24)

se-book
- [css/textbook.css](https://github.com/se-edu/se-book/blob/9a29a6eb94c113acf6b720c915176f1421d713a6/css/textbook.css#L20-L24)

TE-3201:
- [`programming/css/programming.css`](https://github.com/nus-te3201/website/blob/ee4b2897d8591b66f11db6394653501a87ac49a8/programming/css/programming.css#L20-L24)
- [`css/main.css`](https://github.com/nus-te3201/website/blob/ee4b2897d8591b66f11db6394653501a87ac49a8/css/main.css#L20-L24)

Now radio list items and task list items, that are not in a question-wrapper, will not have a "bullet-point" and we don't have to explicitly write css for it.
