### ISSUE TITLE
Should alpha/beta/pre-release versioning tags also trigger UG update?

### ISSUE THREAD

**Issue by tlylt** [MarkBind/markbind#1776]
**Is your request related to a problem?**
Currently, we are using 
```yml
name: CI
on:
  push:
    branches:
      - master
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
 ```
which will match major.minor.patch, per [semantic versioning spec](https://semver.org/), also similar to an [example given in GitHub docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-branches-and-tags).

Previously, our Travis yml was using: `condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+`

If we were to release a tag that is `v3.1.1-beta.1`, the current UG deployment step in the workflow might not be triggered. Is this a concern?

**Alternative**
Something simpler like
```yml
on:
  push:
    tags:
    - '*'
```
will be able to match all tags with caveat that a wrong tag might also trigger the release
