### ISSUE TITLE
Standardize choice of alert types in documentation

### ISSUE THREAD

**Issue by ang-zeyu** [MarkBind/markbind#2089]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Is your feature request related to a problem? Please describe.

The documentation uses all sorts of alert `type`s currently, making for an inconsistent reading experience.

### Describe the solution you'd like

Standardize all the alert types to something. Purely imo, seamless looks the best https://github.com/MarkBind/markbind/pull/1019.

Or, think of a consistent way or guideline to use these different types of alerts in our documentation, and document it clearly in the dev guide.

**Comment by yucheng11122017** [comment]
Hi @ang-zeyu can I check that by "alert" you mean the boxes in the documentation such as the image below? 
![image](https://user-images.githubusercontent.com/77204346/215446521-b70fbd63-42f7-4735-92ca-d6a5a5aee129.png)

**Comment by ang-zeyu** [comment]
Yes, sorry, "boxes" would be more accurate. "alerts" is the bootstrap version.

**Comment by yucheng11122017** [comment]
Hi @ang-zeyu, is this ok for the standardization? 

1. ```<box type="warning" seamless>```: When the lack of this knowledge will likely cause problems for users 
Eg. 
```
<box type="warning" header="#### Using production build" seamless>
In production build, Vue does not perform hydration check. Any errors resulting from hydration will trigger full CSR without warning. MarkBind **uses the development build by default** when you serve it in development mode (`-d` option).
</box>
```

2. ```<box type="tip" seamless>```:Good advice for users which will make things easier for them 
Eg. 
````
<box type="tip" id="markbind-action-tip">

MarkBind provides a helper GitHub Action that you can use to simplify your workflow file. A sample workflow file utilizing the action is as follows:
```yml
name: Deploy MarkBind Site
on:
  push:
    branches: master

jobs: 
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build & Deploy MarkBind site
        uses: MarkBind/markbind-action@v2
        with:
          token: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
```
Read the [action documentation](https://github.com/MarkBind/markbind-action#readme) to understand the various configuration options.
</box> 
````

3. ```<box type="info" seamless>```: Other additional information

Eg. 
```
<box type="info" seamless>

Note that `Layout` instances do not generate any output files directly, but rather, they store intermediate processing results to be used in a `Page`.
</box>

```
