### ISSUE TITLE
.card-seamless CSS in NestedPanel does not target any element

### ISSUE THREAD

**Issue by tlylt** [MarkBind/markbind#2324]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Tell us about your environment

Windows 10

### MarkBind version

Master branch

### Describe the bug and the steps to reproduce it

In [packages/vue-components/src/panels/NestedPanel.vue](https://github.com/MarkBind/markbind/blob/master/packages/vue-components/src/panels/NestedPanel.vue#L282), there are a few CSS targeting .card-seamless
```css
     .card-seamless {
        padding: 0;
    }
    .card.card-seamless {
        box-shadow: none;
        border: none;
    }

    .card-seamless > .card-heading {
        padding: 0;
    }

    .card-seamless > .card-collapse > hr {
        margin: 0;
        width: calc(100% - 27px);
    }

    .card-seamless > .card-collapse > .card-body {
        padding: 10px 0;
    }

    .card-body > .collapse-button {
        margin-bottom: 13px;
        margin-top: 5px;
        opacity: 0.2;
    }

    .card-body > .collapse-button:hover {
        opacity: 1;
    }

    .card-seamless > .card-collapse > .card-body > .collapse-button {
        position: relative;
        top: 22px;
    }
```

However, we don't seem to have any element with the `card-seamless` class. Meaning: whatever CSS effects targeting the card-seamless elements are **not** working.

At least one minor UI difference that I observed after manually putting the `card-seamless` class in for a panel element is that the placement of the caret shifts to the side:
Before:
![image](https://github.com/MarkBind/markbind/assets/41845017/bbfff928-9387-46e6-b946-fb445edfcc17)

After:
(due to .card-seamless {
    padding: 0;
})

![image](https://github.com/MarkBind/markbind/assets/41845017/015d726e-5151-4ceb-8158-28a8fd17a8fe)

Question: is the "Before" or "After" version the intended/preferred styling?

I traced the code back to https://github.com/MarkBind/vue-strap/pull/117 where the `.card-seamless` was introduced, which also don't seem to have such class -> suggesting that it has not been in action since inception?

@ang-zeyu @damithc do you by any chance have any recollection wrt to this?

### Expected behavior

- No unused CSS
- retain intended style if any

### Anything else?

If found to be unnecessary CSS, we should remove them accordingly.
