### ISSUE TITLE
Update UG GitHub Actions deployment sample workflow file 

### ISSUE THREAD

**Issue by gerteck** [MarkBind/markbind#2555]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Tell us about your environment

Windows 11

### MarkBind version

5.5.2

### Describe the bug and the steps to reproduce it

While exploring MarkBind as a User, I was following the [UG to deploy via GitHub Actions](https://markbind.org/userGuide/deployingTheSite.html#deploying-via-github-actions) to deploy my site on GitHub Pages for a newly set up repository. As the workflow permissions default to read-only (Settings>Actions>General), github-actions is not able to write to `gh-pages`.

### Steps to reproduce
1. Init new repo for new Markbind site
1. Use template workflow file 
1. push to github for deployment

### Bug/Nit description
Default GitHub Token Permissions:
```
GITHUB_TOKEN Permissions
  Contents: read
  Metadata: read
  Packages: read
```
Error 403 Forbidden:
```
info: Build success!
error: uncaughtException: remote: Permission to gerteck/repo-name/git denied to github-actions[bot].
fatal: unable to access 'https://github.com/user-name/repo-name.git/': The requested URL returned error: 403
ProcessError: remote: Permission to gerteck/mb-dev.git denied to github-actions[bot].
```

Proposed changes to UG:
```
name: Deploy MarkBind Site
on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    name: test
+    permissions: 
+      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm i -g markbind-cli
      - run: markbind deploy --ci
```
Additionally, workflow reports success when the deployment can be considered to be erroneous, which has been raised in #1863.

While I don't think it is a big bug, perhaps a nit, but I think it would help to improve the onboarding process and make it easier for users to get started with MarkBind until they are more familiar configuring their own workflow.

### Expected behavior

Deployment on github pages success:
```
info: Build success!
info: The website has been deployed at: https://user.github.io/repo-name
```
