### ISSUE TITLE
Content getting cut off when converted to pdf

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#418]
v1.12.0

Example:
![image](https://user-images.githubusercontent.com/1673303/43990419-4d10b360-9d8e-11e8-9da2-2a9e6e55849f.png)

source: https://nus-cs2103-ay1819s1.github.io/cs2103-website/se-book-adapted/chapters-printable/specifyingRequirements-printable.html

**Comment by yamgent** [comment]
Was able to get it to work if I also add `max-width` for `#content-wrapper` ID inside `css/textbook.css`:

```css
@media print {
    .website-content {
        max-width: 100%;
    }

    #content-wrapper {
        max-width: 100%;
    }

    ... other stuff here ...
}
```
