### ISSUE TITLE
User guide: explain how to hide minimized panels in print view

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#419]
Is it possible to automatically hide minimized panels in the print view?

**Comment by acjh** [comment]
Minimized panels (wrapped in `<span class="card-container">`) appear as a `<div class="morph">` element.

```css
@media print {
    .card-container > .morph {
        display: none;
    }
}
```

@yamgent @Chng-Zhi-Xuan MarkBind/vue-strap#53 should have kept the `panel-` classes for semantics, especially since they are not affected by Bootstrap 4 styles.
