### ISSUE TITLE
Add a 'peek' mode for panels

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#905]
Current: panels have expanded, collapsed, and minimized modes.
Suggestion: we can also support a 'peek' (or 'preview') where just a bit of the content is shown.

e.g., 
![image](https://user-images.githubusercontent.com/1673303/60225932-89d11c80-98bb-11e9-95b7-02043f489f1a.png)

or
![image](https://user-images.githubusercontent.com/1673303/60225979-c69d1380-98bb-11e9-9710-818f7ff2bfc5.png)

**Comment by damithc** [comment]
Another idea:
![image](https://user-images.githubusercontent.com/1673303/61614263-df6bcf80-ac95-11e9-99b6-7f89d10d6e08.png)

**Comment by le0tan** [comment]
![image](https://user-images.githubusercontent.com/28982486/72502849-477e2580-3875-11ea-9bf7-1e61d9f7ab03.png)

The visuals can be achieved using the following CSS:

```css
div#test {
    overflow: hidden;
    height: 200px;
}

#test:after {
    content: "";
    display: block;
    position: absolute;
    width: 100%;
    height: 10%;
    bottom: 0;
    background: linear-gradient(transparent, #FFF) left repeat;
}
```
